### ISSUE TITLE
Why not build into the serverless / serverless-offline ecosystem

### ISSUE THREAD

**Issue by goldcaddy77** [AlexSapoznikov/alexa-express-starter-kit#1]
Hey, awesome job on the project and great README! Curious why you decided to build this standalone vs in the serverless / serverless-offline ecosystem as a plugin now that serverless supports Alexa skills?

- https://github.com/serverless/examples/tree/master/aws-node-alexa-skill
- https://github.com/dherault/serverless-offline

I've been working with serverless offline dynamodb, elasticsearch, lambda (including scheduled), and api gateway and it's been a treat. Would love to see Alexa join the fun :)

**Comment by AlexSapoznikov** [comment]
Hey!

To be honest, I wasn't aware of serverless ecosystem at the time you posted this comment. I now have tried and tested it. Setting it up for me took some hours (bumped into different situations where I just could get it to run). Overall, I like serverless ecosystem, but I think that current standalone is a faster and easier start for beginners. I will keep an eye on serverless though to see if I could and should integrate it in the future.

Thanks for a comment :)

**Comment by goldcaddy77** [comment]
Cool, sounds good.  Thanks for researching.
